name: CI cache advance

on: workflow_dispatch

jobs:
  ci:
    name: Running CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.0.2

      - uses: actions/setup-node@v3.1.1
        with:
          node-version: v16.14.2

      - name: Get node version
        id: node
        run: |
          echo "::set-output name=version::$(node -v)"
    - run: yarn install
      - name: Get node_modules cache
        uses: actions/cache@v3.0.2
        id: node_modules
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}-${{ steps.node.outputs.version }}
  name: "Firmware Dump by DumprX"
  only_if: $CIRRUS_REPO_OWNER == 'DumprX'

  container:
      image: ghcr.io/sushrut1101/docker:arch
      cpu: 4
      memory: 16G

  Clone_script:
      - git clone --depth=1 --single-branch https://github.com/DumprX/DumprX.git

  Setup_script:
      - git config --global user.name "Sushrut1101"
      - git config --global user.email "guptasushrut@gmail.com"
      - cd DumprX
      - sudo bash setup.sh

  DumprX_script:
      - cd DumprX || echo "Already in the Directory"
      - ./dumper.sh $(< ${CIRRUS_WORKING_DIR}/ROM_URL.txt)

  name: Zip Dump
      -zip -r Dumpfile.zip DumprX
      
  name: Upload to Release
      uses: softprops/action-gh-release@master
      with:
        files: |
        Dumpfile.zip
        name: Unofficial DUMp 
        tag_name: ${{ github.run_id }

      ### - run: yarn test
